#! /bin/sh
# **************************************************************************
# Regenerate all files which are constructed by the autoconf, automake
# and libtool tool-chain. Note: only developers should need to use
# this script.
#
# Authors:
#   Lars J. Aas <larsa@sim.no>
#   Morten Eriksen <mortene@sim.no>
#

wd=`echo "$0" | sed 's,[^/]*$,,g'`
me=`echo "$0" | sed 's,.*/,,g'`

cd $wd
if test ! -f ./$me; then
  echo >&2 "$me: error: unexpected problem with your shell - bailing out"
  exit 1
fi

package=cfg/bootstrap.tar
verbose=false

if test x"$@" = x"" -a ! -f cfg/mkinstalldirs; then
  echo "$me: assuming '--add' was meant."
  set : --add
  shift
fi

for arg in $@; do
  case "$arg" in
  -v | --verbose)
    verbose=true
    ;;
  --clean)
    ( $verbose && set -x;
      rm -f aclocal.m4 config.h.in configure stamp-h*
      rm -f cfg/{config.guess,config.sub,depcomp,install-sh,ltconfig,ltmain.sh,missing,mkinstalldirs}
      find . -name Makefile.in -print | xargs rm -f
    )
    exit 0
    ;;
  --add)
    AUTOMAKE_ADD="--add-missing --copy"
    ;;
  *)
    echo >&2 "$me: error: don't understand argument \"$arg\""
    DIE=true
    ;;
  esac
done

PROJECT=SoGtk

MACRODIR=cfg/m4

SUBPROJECTS="$MACRODIR data"
SUBPROJECTNAMES="SoGtkMacros SoGtkData"

: ${AUTOMAKE_ADD=}

AUTOCONF_VER=2.49c     # Autoconf from CVS
AUTOMAKE_VER=1.4[abc]  # Automake from CVS
LIBTOOL_VER=1.3.5
GETTEXT_VER=0.10.35

echo "Checking the installed configuration tools..."

if test -z "`autoconf --version | grep \" $AUTOCONF_VER\" 2> /dev/null`"; then
  cat <<END

  You must have autoconf version $AUTOCONF_VER installed to
  generate configure information and Makefiles for $PROJECT.
END
    DIE=true
fi

if test -z "`automake --version | grep \" $AUTOMAKE_VER\" 2> /dev/null`"; then
  cat <<END

  You must have automake version $AUTOMAKE_VER installed to
  generate configure information and Makefiles for $PROJECT.

  The Automake version we are using is a development version
  "frozen" from the CVS repository at 2000-01-13. You can get
  it here:"

END
    DIE=true
fi

if test -z "`libtool --version | grep \" $LIBTOOL_VER \" 2> /dev/null`"; then
  cat <<END

  You must have libtool version $LIBTOOL_VER installed to
  generate configure information and Makefiles for $PROJECT.

  Get ftp://ftp.gnu.org/pub/gnu/libtool/libtool-1.3.5.tar.gz
END
    DIE=true
fi

if test -z "`gettextize --version | grep \" $GETTEXT_VER\" 2> /dev/null`"; then
  cat <<END

  You must have gettextize version $GETTEXT_VER installed to
  generate gettext support files for $PROJECT.
END
    DIE=true
fi

set $SUBPROJECTNAMES
num=1
for project in $SUBPROJECTS; do
  test -d $project || {
    cat <<END

  Could not find subdirectory '$project'.
  It was probably added after you initially fetched $PROJECT.
  To add the missing module, run 'cvs co $1' from the $PROJECT
  base directory.

  To do a completely fresh cvs checkout of the whole $PROJECT module,
  (if all else fails), remove $PROJECT and run:

    cvs -z3 -d :pserver:cvs@cvs.sim.no:/export/cvsroot co -P $PROJECT
END
    DIE=true
  }
  num=`expr $num + 1`
  shift
done

${DIE=false} && echo "" && echo "$me: faking the bootstrap process..." &&
  gzip -cd $package.gz | tar xf - && exit 0

# **************************************************************************

# generate aclocal.m4 (must be done before gettextize)
echo "Running aclocal..."
( $verbose && set -x;
  aclocal -I $MACRODIR
)

# generate gettext support
echo "Running gettextize..."
( ( $verbose && set -x;
  bakdir=intl-bak.$$
  mkdir $bakdir || exit 1
  cp intl/.cvsignore intl/CVS/* $bakdir
  gettextize -f -c 1>&3 && \
  cp po/Makefile.in.in po/Makefile.in.in~ && \
  sed \
      -e 's%\$(top_srcdir)/mkinstalldirs%\$(top_srcdir)/cfg/mkinstalldirs%g' \
      -e 's%MKINSTALLDIRS =.*$%MKINSTALLDIRS = \$(top_srcdir)/cfg/mkinstalldirs%' \
      -e 's%--add-comments %%' \
      -e 's%--files-from%-C --files-from%' \
	< po/Makefile.in.in > po/Makefile.in.in~ && \
  mv po/Makefile.in.in~ po/Makefile.in.in
  cp $bakdir/.cvsignore intl/
  rm $bakdir/.cvsignore
  mkdir intl/CVS
  cp $bakdir/* intl/CVS/
  rm $bakdir/*
  rmdir $bakdir
) 3>&1 1>&2 2>&3 | \
  grep -v 'adding the necessary$' | \
  grep -v 'progtest.m4 from$' | \
  grep -v '^the directory ' \
) 3>&1 1>&2 2>&3

# generate config.h.in template
echo "Running autoheader..."
( ( $verbose && set -x;
  autoheader
) 3>&1 1>&2 2>&3 | grep -v 'is unchanged$' ) 3>&1 1>&2 2>&3

# generate Makefile.in templates
echo "Running automake..."
( ( $verbose && set -x;
  automake $AUTOMAKE_ADD
) 3>&1 1>&2 2>&3 | grep -v 'directory should not' ) 3>&1 1>&2 2>&3

# generate configure script
echo "Running autoconf..."
( $verbose && set -x;
  autoconf
)

